parameters:
  name: ''
  displayName: ''
  vmImage: ''
  scriptFileName: ''
  scriptArgs: 'all'
  outputDirectory : ''
  artifactName: ''
  timeoutInMinutes: 120

jobs:
  - job: ${{ parameters.name }}
    displayName: ${{ parameters.displayName }}
    timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
      - checkout: self  # self represents the repo where the initial Pipelines YAML file was found
        clean: false  # whether to fetch clean each time
        submodules: recursive  # set to 'true' for a single level of submodules or 'recursive' to get submodules of submodules
        persistCredentials: true

      - task: UseDotNet@2
        displayName: 'Use .NET Core SDK 3.1.105'
        inputs:
          packageType: sdk
          version: 3.1.105

      # Linux
      # Start Azurite (Azure simulator) in Linux
      - task: ShellScript@3
        displayName: 'Install Azurite'
        inputs:
          targetType: inline
          script: |
            sudo npm install -g azurite
        condition: in( variables['Agent.OS'], 'Linux', 'Darwin' )
      - task: ShellScript@3
        displayName: 'Run Azurite'
        inputs:
          targetType: inline
          script: |
            sudo azurite --silent --location /tmp --debug /tmp/debug.log &
        condition: in( variables['Agent.OS'], 'Linux', 'Darwin' )
      
      # Do build
      - task: Bash@3 
        displayName: Linux / OSX Build
        inputs:
          filePath: ${{ parameters.scriptFileName }}
          arguments: ${{ parameters.scriptArgs }}
        continueOnError: true
        condition: in( variables['Agent.OS'], 'Linux', 'Darwin' )


      # Windows
      # Start Azure Storage Emulator in windows
      - task: CmdLine@2
        displayName: 'Run Azure Storage Emulator'
        inputs:
          script: |
            "%ProgramFiles(x86)%\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" init /server "(localdb)\MsSqlLocalDb"
            "%ProgramFiles(x86)%\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" start
        condition: eq( variables['Agent.OS'], 'Windows_NT' )

      # Do build
      - task: BatchScript@1
        displayName: Windows Build
        inputs:
          filename: ${{ parameters.scriptFileName }}
          arguments: ${{ parameters.scriptArgs }}
        continueOnError: true
        condition: eq( variables['Agent.OS'], 'Windows_NT' )


      # Common steps
      - task: PublishTestResults@2
        inputs:
          testRunner: VSTest
          testResultsFiles: '**/*.trx' #TestResults folder usually
          testRunTitle: ${{ parameters.name }}
          mergeTestResults: true
      - task: CopyFiles@2
        displayName: 'Copy Build Output'
        inputs:
          sourceFolder: ${{ parameters.outputDirectory }}
          contents: '**\*'
          targetFolder: $(Build.ArtifactStagingDirectory)
          continueOnError: boolean  # 'true' if future steps should run even if this step fails; defaults to 'false'
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: ${{ parameters.artifactName }}
      - script: 'echo 1>&2'
        failOnStderr: true
        displayName: 'If above is partially succeeded, then fail'
        condition: eq(variables['Agent.JobStatus'], 'SucceededWithIssues')